import {
  Utensils, Car, ShoppingBag, Film, Zap, HeartPulse, GraduationCap, Plane, Gift, Dumbbell, Phone, Droplets,
  CircleMinus, Briefcase, Wallet, TrendingUp, RotateCcw, Home, Coffee, PawPrint, Wrench, Store, Banknote, Landmark, Smartphone, PiggyBank,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, typeof Utensils> = {
  food: Utensils,
  transport: Car,
  shopping: ShoppingBag,
  entertainment: Film,
  utilities: Zap,
  health: HeartPulse,
  education: GraduationCap,
  travel: Plane,
  gift: Gift,
  fitness: Dumbbell,
  phone: Phone,
  water: Droplets,
  other_expense: CircleMinus,
  salary: Briefcase,
  freelance: Wallet,
  investment: TrendingUp,
  gift_income: Gift,
  other_income: CircleMinus,
  refund: RotateCcw,
  rent: Home,
  coffee: Coffee,
  pet: PawPrint,
  repair: Wrench,
  selling: Store,
  cash: Banknote,
  bank: Landmark,
  ewallet: Smartphone,
  savings: PiggyBank,
};
