import {
  Utensils, Car, ShoppingBag, Clapperboard, Zap, HeartPulse, GraduationCap, Plane, Gift, Dumbbell, Phone, Droplets,
  HelpCircle, CirclePlus, Briefcase, Wallet, TrendingUp, RotateCcw, Home, Coffee, PawPrint, Wrench, Store, Banknote, Landmark, Smartphone, PiggyBank, Trophy,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, typeof Utensils> = {
  food: Utensils,
  transport: Car,
  shopping: ShoppingBag,
  entertainment: Clapperboard,
  utilities: Zap,
  health: HeartPulse,
  education: GraduationCap,
  travel: Plane,
  gift: Gift,
  fitness: Dumbbell,
  phone: Phone,
  water: Droplets,
  other_expense: HelpCircle,
  salary: Briefcase,
  bonus: Trophy,
  freelance: Wallet,
  investment: TrendingUp,
  gift_income: Gift,
  other_income: CirclePlus,
  refund: RotateCcw,
  rent: Home,
  coffee: Coffee,
  pet: PawPrint,
  repair: Wrench,
  selling: Store,
  cash: Banknote,
  bank: Landmark,
  ewallet: Smartphone,
  savings: PiggyBank,
};
